const { jsPDF } = require('jspdf');
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, BorderStyle } = require('docx');
const { Builder } = require('xml2js');
const { sendFormEmail } = require('../utils/email');
const { saveExport } = require('../utils/mongodb');
const { v4: uuidv4 } = require('uuid');

async function exportOccurrenceReport(formData, paramedicProfile) {
  console.log('[ExportAgent] Generating Occurrence Report PDF...');

  const doc = new jsPDF();
  const fields = formData.fields || {};
  const margin = 20;
  const labelX = margin;
  const valueX = 85;
  const maxWidth = 95;
  let y = 20;

  const accentR = 229; const accentG = 62; const accentB = 62; // #e53e3e

  // Form header (matches app: icon area + title + subtitle)
  doc.setFillColor(255, 240, 240); // light red tint
  doc.roundedRect(margin, y - 6, 44, 22, 3, 3, 'F');
  doc.setDrawColor(accentR, accentG, accentB);
  doc.setLineWidth(0.5);
  doc.roundedRect(margin, y - 6, 44, 22, 3, 3, 'S');
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(40, 40, 40);
  doc.text('Occurrence Report', margin + 50, y + 2);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Incident Documentation', margin + 50, y + 10);
  y += 28;

  const addSection = (label) => {
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(0.3);
    doc.line(margin, y, 190, y);
    y += 4;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 100, 100);
    doc.text(label.toUpperCase(), margin, y + 3);
    y += 12;
  };

  const addField = (label, value, required = false) => {
    const v = value != null && value !== '' ? String(value) : '—';
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text(`${label}${required ? ' *' : ''}`, labelX, y + 4);
    doc.setFillColor(248, 248, 250);
    doc.setDrawColor(230, 230, 235);
    doc.roundedRect(valueX - 2, y - 3, 105, 10, 2, 2, 'FD');
    doc.setTextColor(40, 40, 40);
    doc.text(v, valueX + 101, y + 4, { align: 'right', maxWidth: 99 });
    y += 12;
    if (y > 270) { doc.addPage(); y = 20; }
  };

  addSection('INCIDENT DETAILS');
  addField('Date', fields.date?.value, true);
  addField('Time', fields.time?.value, true);
  addField('Call Number', fields.call_number?.value);
  addField('Occurrence Type', fields.occurrence_type?.value, true);
  addField('Reference #', fields.occurrence_reference?.value);
  addField('Severity', fields.severity?.value, true);

  addSection('VEHICLE & LOCATION');
  addField('Vehicle Number', fields.vehicle_number?.value);
  addField('Vehicle Description', fields.vehicle_description?.value);
  addField('Location', fields.location?.value, true);
  addField('City', fields.city?.value, true);
  addField('Province', fields.province?.value);

  addSection('PARAMEDIC INFO');
  addField('Service', fields.service?.value);
  addField('Role', fields.role?.value, true);
  addField('Badge Number', fields.badge_number?.value, true);
  addField('Paramedic Name', fields.paramedic_name?.value, true);

  addSection('REPORT');
  addField('Injuries Reported', fields.injuries_reported?.value, true);
  addField('Equipment Damage', fields.equipment_damage?.value, true);
  addField('Supervisor Notified', fields.supervisor_notified?.value);
  addField('Other Services', fields.other_services?.value);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  doc.text('Description *', labelX, y + 4);
  y += 8;
  doc.setFillColor(248, 248, 250);
  doc.setDrawColor(230, 230, 235);
  const descText = String(fields.description?.value || 'N/A');
  const descLines = doc.splitTextToSize(descText, maxWidth);
  const descH = Math.max(10, descLines.length * 5);
  doc.roundedRect(valueX - 2, y - 3, 105, descH, 2, 2, 'FD');
  doc.setTextColor(40, 40, 40);
  doc.text(descLines, valueX, y + 3);
  y += descH + 10;

  doc.setTextColor(80, 80, 80);
  doc.text('Action Taken *', labelX, y + 4);
  y += 8;
  const actionText = String(fields.action_taken?.value || 'N/A');
  const actionLines = doc.splitTextToSize(actionText, maxWidth);
  const actionH = Math.max(10, actionLines.length * 5);
  doc.roundedRect(valueX - 2, y - 3, 105, actionH, 2, 2, 'FD');
  doc.text(actionLines, valueX, y + 3);
  y += actionH + 10;

  addField('Resolution', fields.resolution?.value);
  addField('Management Notes', fields.management_notes?.value);

  y += 8;
  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, 190, y);
  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text(`Generated by ParaHelper | ${new Date().toISOString()} | Locked Record`, 105, y, { align: 'center' });

  const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
  const fileName = `OccurrenceReport_${paramedicProfile.badge_number}_${Date.now()}.pdf`;

  const emailResult = await sendFormEmail({
    to: 'team01@effectiveai.net',
    subject: `[ParaHelper] Occurrence Report - Unit ${paramedicProfile.unit} - ${fields.date?.value || new Date().toLocaleDateString()}`,
    body: `Occurrence Report submitted by ${paramedicProfile.first_name} ${paramedicProfile.last_name} (${paramedicProfile.badge_number}).\n\nType: ${fields.occurrence_type?.value}\nSeverity: ${fields.severity?.value}\nLocation: ${fields.location?.value}, ${fields.city?.value}\n\nPlease find the PDF attached.`,
    attachments: [{ filename: fileName, content: pdfBuffer }]
  });

  const exportRecord = {
    export_id: `EXP-${uuidv4().substring(0, 8)}`,
    form_id: formData.occurrence_id || `OCC-${uuidv4().substring(0, 8)}`,
    paramedic_id: paramedicProfile.paramedic_id,
    file_type: 'pdf',
    file_name: fileName,
    email_sent_to: 'team01@effectiveai.net',
    email_status: emailResult.success ? 'sent' : 'failed',
    sent_at: new Date(),
    retry_count: 0
  };
  await saveExport(exportRecord);

  console.log(`[ExportAgent] Occurrence Report exported: ${fileName}`);
  return { success: true, fileName, emailResult, pdfBase64: pdfBuffer.toString('base64') };
}

async function exportTeddyBear(formData, paramedicProfile) {
  console.log('[ExportAgent] Generating Teddy Bear PDF + XML...');

  const fields = formData.fields || {};
  const doc = new jsPDF();
  const margin = 20;
  const labelX = margin;
  const valueX = 85;
  const maxWidth = 95;
  let y = 20;

  const accentR = 66; const accentG = 153; const accentB = 225; // #4299e1 blue

  // Form header (matches app: blue icon + title + subtitle)
  doc.setFillColor(235, 245, 255); // light blue tint
  doc.roundedRect(margin, y - 6, 44, 22, 3, 3, 'F');
  doc.setDrawColor(accentR, accentG, accentB);
  doc.setLineWidth(0.5);
  doc.roundedRect(margin, y - 6, 44, 22, 3, 3, 'S');
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(40, 40, 40);
  doc.text('Teddy Bear Tracking', margin + 50, y + 2);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Comfort Item Record', margin + 50, y + 10);
  y += 28;

  const addSection = (label) => {
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(0.3);
    doc.line(margin, y, 190, y);
    y += 4;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 100, 100);
    doc.text(label.toUpperCase(), margin, y + 3);
    y += 12;
  };

  const addField = (label, value, required = false) => {
    const v = value != null && value !== '' ? String(value) : '—';
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text(`${label}${required ? ' *' : ''}`, labelX, y + 4);
    doc.setFillColor(248, 248, 250);
    doc.setDrawColor(230, 230, 235);
    doc.roundedRect(valueX - 2, y - 3, 105, 10, 2, 2, 'FD');
    doc.setTextColor(40, 40, 40);
    doc.text(v, valueX + 101, y + 4, { align: 'right', maxWidth: 99 });
    y += 12;
    if (y > 270) { doc.addPage(); y = 20; }
  };

  addSection('EVENT DETAILS');
  addField('Date & Time', fields.date_time?.value, true);
  addField('Unit', fields.unit_id?.value);
  addField('Location', fields.location?.value);
  addField('City', fields.city?.value);
  addField('Province', fields.province?.value);

  addSection('MEDIC INFO');
  addField('Primary Medic (First)', fields.primary_medic_first?.value, true);
  addField('Primary Medic (Last)', fields.primary_medic_last?.value, true);
  addField('Badge Number', fields.medic_number?.value, true);
  addField('Second Medic', fields.second_medic?.value);

  addSection('RECIPIENT');
  addField('Recipient Age', fields.recipient_age?.value, true);
  addField('Recipient Gender', fields.recipient_gender?.value, true);
  addField('Recipient Type', fields.recipient_type?.value, true);
  addField('Notes', fields.notes?.value);

  y += 8;
  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, 190, y);
  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text(`Generated by ParaHelper | ${new Date().toISOString()}`, 105, y, { align: 'center' });

  const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

  const xmlBuilder = new Builder();
  const xmlObj = {
    teddy_bear_tracking: {
      event_datetime: fields.date_time?.value || '',
      primary_medic: {
        first_name: fields.primary_medic_first?.value || '',
        last_name: fields.primary_medic_last?.value || '',
        badge_number: fields.medic_number?.value || ''
      },
      second_medic: fields.second_medic?.value || '',
      unit_id: fields.unit_id?.value || '',
      recipient: {
        age: fields.recipient_age?.value || '',
        gender: fields.recipient_gender?.value || '',
        type: fields.recipient_type?.value || ''
      },
      location: {
        address: fields.location?.value || '',
        city: fields.city?.value || '',
        province: fields.province?.value || ''
      },
      notes: fields.notes?.value || ''
    }
  };
  const xmlString = xmlBuilder.buildObject(xmlObj);
  const xmlBuffer = Buffer.from(xmlString, 'utf-8');

  const pdfName = `TeddyBear_${paramedicProfile.badge_number}_${Date.now()}.pdf`;
  const xmlName = `TeddyBear_${paramedicProfile.badge_number}_${Date.now()}.xml`;

  const emailResult = await sendFormEmail({
    to: 'team01@effectiveai.net',
    subject: `[ParaHelper] Teddy Bear Tracking - Unit ${paramedicProfile.unit} - ${fields.date_time?.value || new Date().toLocaleDateString()}`,
    body: `Teddy Bear Tracking Form submitted by ${paramedicProfile.first_name} ${paramedicProfile.last_name}.\n\nRecipient: ${fields.recipient_type?.value}, Age ${fields.recipient_age?.value}\n\nPDF and XML attached.`,
    attachments: [
      { filename: pdfName, content: pdfBuffer },
      { filename: xmlName, content: xmlBuffer }
    ]
  });

  const exportRecord = {
    export_id: `EXP-${uuidv4().substring(0, 8)}`,
    form_id: formData.tracking_id || `TBT-${uuidv4().substring(0, 8)}`,
    paramedic_id: paramedicProfile.paramedic_id,
    file_type: 'pdf+xml',
    file_name: `${pdfName}, ${xmlName}`,
    email_sent_to: 'team01@effectiveai.net',
    email_status: emailResult.success ? 'sent' : 'failed',
    sent_at: new Date(),
    retry_count: 0
  };
  await saveExport(exportRecord);

  console.log(`[ExportAgent] Teddy Bear exported: ${pdfName} + ${xmlName}`);
  return { success: true, pdfName, xmlName, emailResult, pdfBase64: pdfBuffer.toString('base64') };
}

async function exportStatusReport(formData, paramedicProfile) {
  console.log('[ExportAgent] Generating Status Report Word Document...');

  // Support both form_data.fields and flat statusData
  const fields = formData?.fields || formData || {};
  const getVal = (k) => {
    const v = fields[k];
    return (v && typeof v === 'object' && 'value' in v) ? v.value : v;
  };
  const flatData = {
    acr_completion: getVal('acr_completion'),
    acr_unfinished: getVal('acr_unfinished'),
    driver_license: getVal('driver_license'),
    vaccination: getVal('vaccination'),
    vaccination_issues: getVal('vaccination_issues'),
    education: getVal('education'),
    cme_outstanding: getVal('cme_outstanding'),
    uniform_status: getVal('uniform_status'),
    uniform_credits: getVal('uniform_credits'),
    criminal_record: getVal('criminal_record'),
    acp_cert: getVal('acp_cert'),
    vacation: getVal('vacation'),
    missed_meals: getVal('missed_meals'),
    missed_meals_count: getVal('missed_meals_count'),
    overtime: getVal('overtime'),
    overtime_count: getVal('overtime_count')
  };

  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          children: [
            new TextRun({ text: 'Paramedic Status Report', bold: true, size: 28, font: 'Arial' })
          ],
          spacing: { after: 60 }
        }),
        new Paragraph({
          children: [
            new TextRun({ text: 'Compliance Checklist', size: 22, color: '666666' })
          ],
          spacing: { after: 300 }
        }),
        new Paragraph({
          children: [
            new TextRun({ text: 'STATUS ITEMS', bold: true, size: 18, color: '888888' })
          ],
          spacing: { after: 120 }
        }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              children: ['Item', 'Type', 'Description', 'Status', '#', 'Notes'].map(h =>
                new TableCell({
                  children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, size: 18 })] })],
                  shading: { fill: 'E8E8EC' },
                  borders: { top: { style: BorderStyle.SINGLE }, bottom: { style: BorderStyle.SINGLE }, left: { style: BorderStyle.SINGLE }, right: { style: BorderStyle.SINGLE } }
                })
              )
            }),
            ...buildStatusRows(flatData)
          ]
        }),
        new Paragraph({
          children: [
            new TextRun({ text: `Generated by ParaHelper | ${new Date().toISOString()}`, size: 16, italics: true, color: '999999' })
          ],
          spacing: { before: 400 }
        })
      ]
    }]
  });

  const buffer = await Packer.toBuffer(doc);
  const fileName = `StatusReport_${paramedicProfile.badge_number}_${Date.now()}.docx`;

  const emailResult = await sendFormEmail({
    to: paramedicProfile.email || 'team01@effectiveai.net',
    subject: `[ParaHelper] Status Report - ${paramedicProfile.first_name} ${paramedicProfile.last_name} - ${new Date().toLocaleDateString()}`,
    body: `Paramedic Status Report for ${paramedicProfile.first_name} ${paramedicProfile.last_name}.\n\nPlease review the attached Word document.`,
    attachments: [{ filename: fileName, content: buffer }]
  });

  console.log(`[ExportAgent] Status Report exported: ${fileName}`);
  return { success: true, fileName, emailResult, docxBase64: buffer.toString('base64') };
}

function buildStatusRows(data) {
  if (!data) return [];
  const items = [
    { code: 'ACRc', type: 'ACR Completion', desc: 'Unfinished ACRs/PCRs', status: data.acr_completion, issues: data.acr_unfinished, notes: 'Complete within 24 hours' },
    { code: 'CERT-DL', type: 'Drivers License', desc: 'License Validity', status: data.driver_license, issues: 0, notes: 'Driver License Status' },
    { code: 'CERT-Va', type: 'Vaccinations', desc: 'Required vaccinations', status: data.vaccination, issues: data.vaccination_issues, notes: 'Per guidelines' },
    { code: 'CERT-CE', type: 'Education', desc: 'Continuing Education', status: data.education, issues: data.cme_outstanding, notes: 'CME outstanding' },
    { code: 'UNIF', type: 'Uniform', desc: 'Uniform credits', status: data.uniform_status, issues: data.uniform_credits, notes: 'Available credits' },
    { code: 'CRIM', type: 'Criminal Record', desc: 'CRC Check', status: data.criminal_record, issues: 0, notes: 'Criminal Issue Free' },
    { code: 'ACP', type: 'ACP Status', desc: 'ACP Cert Valid', status: data.acp_cert, issues: 0, notes: 'ACP certification' },
    { code: 'VAC', type: 'Vacation', desc: 'Vacation requests', status: data.vacation, issues: 0, notes: 'Yearly vacation' },
    { code: 'MEALS', type: 'Missed Meals', desc: 'Missed Meal Claims', status: data.missed_meals, issues: data.missed_meals_count, notes: 'Claims outstanding' },
    { code: 'OVER', type: 'Overtime', desc: 'Overtime Requests', status: data.overtime, issues: data.overtime_count, notes: 'Claims outstanding' }
  ];

  return items.map(item => new TableRow({
    children: [item.code, item.type, item.desc, item.status || 'N/A', String(item.issues || 0), item.notes].map(val =>
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: String(val), size: 16 })] })],
        borders: { top: { style: BorderStyle.SINGLE }, bottom: { style: BorderStyle.SINGLE }, left: { style: BorderStyle.SINGLE }, right: { style: BorderStyle.SINGLE } }
      })
    )
  }));
}

module.exports = { exportOccurrenceReport, exportTeddyBear, exportStatusReport };
